name: Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
permissions:
  contents: read

jobs:
  unix_tests:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-18.04, macos-latest, windows-2019, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
    - uses: actions/checkout@v3
    - name: Testing printf
      run: |
        gcc -std=c11 -o test.exe test.c
        ./test.exe
